[2024-05-23T20:25:57.270+0000] {processor.py:161} INFO - Started process (PID=289) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:25:57.272+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:25:57.274+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:25:57.274+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:25:57.281+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:25:57.279+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:25:57.282+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:25:57.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:26:27.466+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:26:27.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:26:27.470+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:26:27.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:26:27.476+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:26:27.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:26:27.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:26:27.500+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:26:57.664+0000] {processor.py:161} INFO - Started process (PID=311) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:26:57.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:26:57.668+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:26:57.668+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:26:57.674+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:26:57.672+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:26:57.675+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:26:57.697+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-05-23T20:27:27.868+0000] {processor.py:161} INFO - Started process (PID=322) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:27:27.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:27:27.871+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:27:27.871+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:27:27.878+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:27:27.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:27:27.879+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:27:27.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:27:58.072+0000] {processor.py:161} INFO - Started process (PID=333) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:27:58.073+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:27:58.076+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:27:58.075+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:27:58.082+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:27:58.081+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:27:58.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:27:58.105+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:28:28.276+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:28:28.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:28:28.281+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:28:28.281+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:28:28.287+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:28:28.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:28:28.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:28:28.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-05-23T20:28:58.489+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:28:58.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:28:58.493+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:28:58.493+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:28:58.500+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:28:58.499+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:28:58.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:28:58.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:29:28.682+0000] {processor.py:161} INFO - Started process (PID=366) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:29:28.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:29:28.687+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:29:28.686+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:29:28.694+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:29:28.692+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:29:28.695+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:29:28.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:29:58.891+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:29:58.892+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:29:58.895+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:29:58.895+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:29:58.901+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:29:58.900+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:29:58.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:29:58.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:30:29.096+0000] {processor.py:161} INFO - Started process (PID=388) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:30:29.097+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:30:29.101+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:30:29.100+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:30:29.109+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:30:29.107+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:30:29.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:30:29.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.052 seconds
[2024-05-23T20:30:59.293+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:30:59.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:30:59.298+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:30:59.298+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:30:59.305+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:30:59.304+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:30:59.307+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:30:59.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.053 seconds
[2024-05-23T20:31:29.466+0000] {processor.py:161} INFO - Started process (PID=410) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:31:29.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:31:29.470+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:31:29.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:31:29.476+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:31:29.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:31:29.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:31:29.493+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.034 seconds
[2024-05-23T20:31:59.643+0000] {processor.py:161} INFO - Started process (PID=421) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:31:59.645+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:31:59.648+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:31:59.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:31:59.654+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:31:59.653+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:31:59.655+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:31:59.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-05-23T20:32:29.846+0000] {processor.py:161} INFO - Started process (PID=431) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:32:29.848+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:32:29.851+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:32:29.850+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:32:29.857+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:32:29.856+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:32:29.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:32:29.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:33:00.042+0000] {processor.py:161} INFO - Started process (PID=442) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:33:00.044+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:33:00.047+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:33:00.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:33:00.053+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:33:00.052+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:33:00.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:33:00.076+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:33:30.247+0000] {processor.py:161} INFO - Started process (PID=453) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:33:30.248+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:33:30.251+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:33:30.251+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:33:30.259+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:33:30.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:33:30.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:33:30.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:34:00.439+0000] {processor.py:161} INFO - Started process (PID=464) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:34:00.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:34:00.444+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:34:00.443+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:34:00.451+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:34:00.449+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:34:00.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:34:00.474+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:34:30.649+0000] {processor.py:161} INFO - Started process (PID=475) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:34:30.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:34:30.653+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:34:30.653+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:34:30.661+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:34:30.659+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:34:30.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:34:30.684+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:35:00.874+0000] {processor.py:161} INFO - Started process (PID=486) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:35:00.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:35:00.877+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:35:00.877+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:35:00.883+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:35:00.882+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:35:00.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:35:00.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.040 seconds
[2024-05-23T20:35:31.069+0000] {processor.py:161} INFO - Started process (PID=497) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:35:31.071+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:35:31.073+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:35:31.073+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:35:31.080+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:35:31.078+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:35:31.081+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:35:31.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:36:01.280+0000] {processor.py:161} INFO - Started process (PID=508) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:36:01.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:36:01.285+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:36:01.285+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:36:01.292+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:36:01.291+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:36:01.293+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:36:01.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:36:31.468+0000] {processor.py:161} INFO - Started process (PID=519) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:36:31.470+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:36:31.473+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:36:31.472+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:36:31.479+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:36:31.478+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:36:31.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:36:31.504+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:37:01.671+0000] {processor.py:161} INFO - Started process (PID=530) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:37:01.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:37:01.675+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:37:01.675+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:37:01.682+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:37:01.681+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:37:01.683+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:37:01.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:37:31.873+0000] {processor.py:161} INFO - Started process (PID=542) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:37:31.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:37:31.877+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:37:31.876+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:37:31.882+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:37:31.881+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:37:31.882+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:37:31.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.032 seconds
[2024-05-23T20:38:02.074+0000] {processor.py:161} INFO - Started process (PID=553) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:38:02.076+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:38:02.078+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:38:02.078+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:38:02.085+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:38:02.083+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:38:02.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:38:02.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:38:32.263+0000] {processor.py:161} INFO - Started process (PID=564) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:38:32.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:38:32.267+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:38:32.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:38:32.274+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:38:32.272+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:38:32.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:38:32.297+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:39:02.448+0000] {processor.py:161} INFO - Started process (PID=575) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:39:02.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:39:02.452+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:39:02.452+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:39:02.460+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:39:02.458+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:39:02.461+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:39:02.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-05-23T20:39:32.657+0000] {processor.py:161} INFO - Started process (PID=586) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:39:32.658+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:39:32.661+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:39:32.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:39:32.667+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:39:32.666+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:39:32.668+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:39:32.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:40:02.844+0000] {processor.py:161} INFO - Started process (PID=597) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:40:02.846+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:40:02.849+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:40:02.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:40:02.855+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:40:02.854+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:40:02.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:40:02.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-05-23T20:40:33.048+0000] {processor.py:161} INFO - Started process (PID=608) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:40:33.050+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:40:33.052+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:40:33.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:40:33.059+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:40:33.057+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:40:33.060+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:40:33.082+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:41:03.268+0000] {processor.py:161} INFO - Started process (PID=619) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:41:03.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:41:03.272+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:41:03.271+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:41:03.279+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:41:03.277+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:41:03.280+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:41:03.302+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:41:33.472+0000] {processor.py:161} INFO - Started process (PID=630) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:41:33.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:41:33.476+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:41:33.475+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:41:33.482+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:41:33.481+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:41:33.483+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:41:33.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:42:03.672+0000] {processor.py:161} INFO - Started process (PID=641) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:42:03.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:42:03.676+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:42:03.676+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:42:03.684+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:42:03.682+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:42:03.685+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:42:03.718+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.055 seconds
[2024-05-23T20:42:33.885+0000] {processor.py:161} INFO - Started process (PID=651) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:42:33.886+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:42:33.889+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:42:33.888+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:42:33.896+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:42:33.894+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:42:33.897+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:42:33.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-05-23T20:43:04.160+0000] {processor.py:161} INFO - Started process (PID=662) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:43:04.162+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:43:04.165+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:43:04.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:43:04.174+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:43:04.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:43:04.175+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:43:04.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.060 seconds
[2024-05-23T20:43:34.334+0000] {processor.py:161} INFO - Started process (PID=673) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:43:34.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:43:34.338+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:43:34.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:43:34.345+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:43:34.344+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:43:34.346+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:43:34.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-05-23T20:44:04.585+0000] {processor.py:161} INFO - Started process (PID=684) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:44:04.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:44:04.589+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:44:04.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:44:04.596+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:44:04.595+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:44:04.597+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:44:04.620+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:44:34.791+0000] {processor.py:161} INFO - Started process (PID=695) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:44:34.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:44:34.796+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:44:34.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:44:34.803+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:44:34.802+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:44:34.804+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:44:34.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.050 seconds
[2024-05-23T20:45:04.984+0000] {processor.py:161} INFO - Started process (PID=706) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:45:04.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:45:04.988+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:45:04.988+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:45:04.996+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:45:04.994+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:45:04.997+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:45:05.024+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-05-23T20:45:35.289+0000] {processor.py:161} INFO - Started process (PID=717) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:45:35.291+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:45:35.294+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:45:35.293+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:45:35.301+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:45:35.299+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:45:35.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:45:35.328+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-05-23T20:46:05.571+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:46:05.572+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:46:05.575+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:46:05.574+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:46:05.582+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:46:05.580+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:46:05.582+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:46:05.606+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:46:35.770+0000] {processor.py:161} INFO - Started process (PID=739) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:46:35.771+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:46:35.773+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:46:35.773+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:46:35.780+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:46:35.779+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:46:35.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:46:35.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:47:05.978+0000] {processor.py:161} INFO - Started process (PID=750) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:47:05.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:47:05.982+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:47:05.982+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:47:05.989+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:47:05.987+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:47:05.990+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:47:06.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:47:36.187+0000] {processor.py:161} INFO - Started process (PID=761) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:47:36.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:47:36.191+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:47:36.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:47:36.198+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:47:36.197+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:47:36.199+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:47:36.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:48:06.381+0000] {processor.py:161} INFO - Started process (PID=772) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:48:06.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:48:06.385+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:48:06.384+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:48:06.392+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:48:06.390+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:48:06.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:48:06.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:48:36.611+0000] {processor.py:161} INFO - Started process (PID=783) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:48:36.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:48:36.615+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:48:36.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:48:36.622+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:48:36.620+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:48:36.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:48:36.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:49:06.806+0000] {processor.py:161} INFO - Started process (PID=794) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:49:06.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:49:06.810+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:49:06.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:49:06.817+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:49:06.815+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:49:06.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:49:06.843+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-05-23T20:49:37.012+0000] {processor.py:161} INFO - Started process (PID=805) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:49:37.013+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:49:37.016+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:49:37.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:49:37.023+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:49:37.022+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:49:37.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:49:37.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.049 seconds
[2024-05-23T20:50:07.216+0000] {processor.py:161} INFO - Started process (PID=816) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:50:07.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:50:07.220+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:50:07.219+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:50:07.226+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:50:07.225+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:50:07.227+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:50:07.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:50:37.410+0000] {processor.py:161} INFO - Started process (PID=827) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:50:37.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:50:37.414+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:50:37.413+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:50:37.420+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:50:37.419+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:50:37.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:50:37.443+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.041 seconds
[2024-05-23T20:51:07.611+0000] {processor.py:161} INFO - Started process (PID=838) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:51:07.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:51:07.615+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:51:07.614+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:51:07.622+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:51:07.620+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:51:07.622+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:51:07.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.042 seconds
[2024-05-23T20:51:37.856+0000] {processor.py:161} INFO - Started process (PID=849) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:51:37.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:51:37.860+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:51:37.860+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:51:37.866+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:51:37.865+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:51:37.867+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:51:37.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.045 seconds
[2024-05-23T20:52:08.079+0000] {processor.py:161} INFO - Started process (PID=860) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:52:08.081+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:52:08.085+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:52:08.084+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:52:08.093+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:52:08.091+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:52:08.094+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:52:08.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.047 seconds
[2024-05-23T20:52:38.275+0000] {processor.py:161} INFO - Started process (PID=871) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:52:38.277+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:52:38.280+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:52:38.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:52:38.287+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:52:38.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:52:38.288+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:52:38.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.046 seconds
[2024-05-23T20:53:08.487+0000] {processor.py:161} INFO - Started process (PID=882) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:53:08.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:53:08.490+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:53:08.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:53:08.498+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:53:08.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:53:08.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:53:08.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.044 seconds
[2024-05-23T20:53:38.704+0000] {processor.py:161} INFO - Started process (PID=893) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:53:38.706+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:53:38.712+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:53:38.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:53:38.727+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:53:38.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:53:38.729+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:53:38.768+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.077 seconds
[2024-05-23T20:54:08.893+0000] {processor.py:161} INFO - Started process (PID=904) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:54:08.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:54:08.897+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:54:08.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:54:08.904+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:54:08.902+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:54:08.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:54:08.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
[2024-05-23T20:54:39.162+0000] {processor.py:161} INFO - Started process (PID=915) to work on /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:54:39.163+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/our_first_dag.py for tasks to queue
[2024-05-23T20:54:39.165+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:54:39.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:54:39.172+0000] {logging_mixin.py:188} INFO - [2024-05-23T20:54:39.171+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/our_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/our_first_dag.py", line 6
    
    ^
IndentationError: expected an indented block after 'with' statement on line 3
[2024-05-23T20:54:39.173+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/our_first_dag.py
[2024-05-23T20:54:39.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/our_first_dag.py took 0.043 seconds
